# helm/monitoring-values.yaml
# Values для kube-prometheus-stack (chart 91.9.0)

grafana:
  adminPassword: admin
  persistence:
    enabled: false
  service:
    type: NodePort
    nodePort: 30300
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi
  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: "1"
      resource: configmap
      watchMethod: WATCH
      skipTlsVerify: true

prometheus:
  service:
    type: NodePort
    nodePort: 30900
  prometheusSpec:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    retention: 7d
    retentionSize: "5GB"
    storageSpec: {}

alertmanager:
  enabled: true
  service:
    type: ClusterIP

prometheus-node-exporter:
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
